name: C++ CI

on:
  push:
    branches: [ '*' ]
    tags: ['*']
  pull_request:
    branches: [ '*' ]
  workflow_dispatch:
    inputs:
      build_type:
        description: Build type
        required: false
        default: 'Debug'
        type: choice
        options:
          - Debug
          - Release
          - RelWithDebInfo
          - MinSizeRel

env:
  BUILD_TYPE: ${{ inputs.build_type || 'Debug' }}
  EXECUTABLE_NAME: "oop"
  INPUT_FILENAME: "tastatura.txt"
  BIN_DIR: "bin"
  BUILD_DIR: "build"
  EXT_DIR: "ext"
  GEN_DIR: "generated"

jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install SFML
        run: |
          sudo apt update
          sudo apt install -y libsfml-dev  # Install SFML

      - name: Configure CMake
        run: |
          cmake -S . -B ${{ env.BUILD_DIR }} -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} -DSFML_DIR=/usr/lib/cmake/SFML

      - name: Build Project
        run: |
          cmake --build ${{ env.BUILD_DIR }}

      - name: Run Tests
        run: |
          ctest --test-dir ${{ env.BUILD_DIR }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.EXECUTABLE_NAME }}"
          path: "${{ env.BUILD_DIR }}"
